{{- if .Values.ksql_db.enabled }}
apiVersion: platform.confluent.io/v1beta1
kind: KsqlDB
metadata:
  name: {{ .Values.kafkaClusterName }}-ksqldb
spec:
  {{- if .Values.ksql_db.enterpriseEdition }}
  kafka:
    spec:
      license:
        secretRef: .Values.ksql_db.license.secretRef
  {{- end }}
  {{- if .Values.ksql_db.tls.enabled }}
  tls:
    secretRef: ksqldb-tls
  {{- end }}
  replicas: {{ .Values.ksql_db.replicas }}
  dataVolumeCapacity: {{ .Values.ksql_db.dataVolumeCapacity }}
  {{- if .Values.image.private_repository }}
  image:
    application: {{ .Values.image.ksql.repository }}:{{ .Values.image.ksql.tag }}
    init: {{ .Values.image.init.repository }}:{{ .Values.image.init.tag }}
    pullSecretRef:
      - {{ .Values.imagePullSecrets }}
  {{ else }}
  image:
    application: confluentinc/cp-ksqldb-server-operator:6.1.0.0
    init: confluentinc/cp-init-container-operator:6.1.0.0
  {{- end }}
  podTemplate:
    resources:
      requests:
        cpu: {{ .Values.ksql_db.resources.requests.cpu }} #1500m
        memory: {{ .Values.ksql_db.resources.requests.memory }} #2000Mi
      limits:
        cpu: {{ .Values.ksql_db.resources.limits.cpu }} #1500m
        memory: {{ .Values.ksql_db.resources.limits.memory }} #2000Mi
{{- end }}