{{- if and ( .Capabilities.APIVersions.Has "monitoring.coreos.com/v1" ) ( .Values.kafka.Monitor.enabled ) }}
apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
{{- if .Values.kafka.Monitor.labels }}
  labels:
{{ toYaml .Values.kafka.Monitor.labels | indent 4}}
{{- end }}
  name: {{ .Values.kafkaClusterName }}-service-monitor
{{- if .Values.kafka.Monitor.namespace }}
  namespace: {{ .Values.kafka.Monitor.namespace }}
{{- end }}
spec:
  endpoints:
  - port: "prometheus"
{{- if .Values.kafka.Monitor.interval }}
    interval: {{ .Values.kafka.Monitor.interval }}
{{- end }}
{{- if .Values.kafka.Monitor.telemetryPath }}
    path: {{ .Values.kafka.Monitor.telemetryPath }}
{{- end }}
{{- if .Values.kafka.Monitor.timeout }}
    scrapeTimeout: {{ .Values.kafka.Monitor.timeout }}
{{- end }}
  namespaceSelector:
    matchNames:
    - {{ .Release.Namespace }}
  selector:
    matchLabels:
      confluent-platform: "true"
      cr-name: "kafka"
      type: "kafka"
{{- end }}


